//Auto-generated by UXL Compiler
//Source: test/controlInControl.uxl.xml

//1#
import "package:rikulo_ui/view.dart";
import "package:rikulo_uxl/uxl.dart";

void main() {
  CIC()[0]..addToDocument();
}

/** Template, CIC, for creating views. */
List<View> CIC({View parent}) { //10#
  List<View> _rv = new List(); View _this_;

  final _c0 = new Control();
  List<View> _c0T({View parent, View beforeChild}) { //11#
    List<View> _rva = new List(); View _this_;

    //11# <View control="Control" layout="type...>
    final _va0 = _this_ = (_c0.view == null ? _c0.view = new View(): new View())
      ..layout.text = '''type:linear'''
      ..style.cssText = '''border: 1px solid blue''';
    if (parent != null)
      parent.addChild(_va0, beforeChild);
    _rva.add(_va0);

    final _ca0 = new Control();
    List<View> _ca0T({View parent, View beforeChild}) { //12#
      List<View> _rvb = new List(); View _this_;

      //12# <View control="Control" style="borde...>
      final _vb0 = _this_ = (_ca0.view == null ? _ca0.view = new View(): new View())
        ..style.cssText = '''border: 1px solid red''';
      if (parent != null)
        parent.addChild(_vb0, beforeChild);
      _rvb.add(_vb0);

      //Inner
      final _vb0_0 = new TextView()
        ..text = '''Inner''';
      _vb0.addChild(_vb0_0);
      return _rvb;
    }
    _ca0.template = _ca0T;
    final _va0_0 = _ca0T(parent: _va0)[0];
    _ca0.onRender();

    //Outer
    final _va0_1 = new TextView()
      ..text = '''Outer''';
    _va0.addChild(_va0_1);
    return _rva;
  }
  _c0.template = _c0T;
  final _v0 = _c0T(parent: parent)[0];
  _rv.add(_v0);
  _c0.onRender();
  return _rv;
}
