name: rikulo_uxl
version: 0.5.2
description: > 
  Rikulo UXL Compiler for compiling UXL files to Dart files.
  Rikulo UXL (User-interface eXtensible Language) allows developers
  to define UI in XML, and to use the MVC pattern to develop applications.
authors:
- Tom Yeh <tomyeh@rikulo.org>
- Simon Pai <simonpai@rikulo.org>
homepage: http://rikulo.org
dependencies:
  args: any
  html5plus: any
  rikulo_ui: any
